apiVersion: v1
kind: Service
metadata:
  name: deis-nsqd
  labels:
    heritage: deis
    app: deis-nsqd
spec:
  ports:
  - port: {{ .Values.http_port }}
    name: http
    targetPort: http
  - port: {{ .Values.tcp_port }}
    name: transport
    targetPort: transport
  selector:
    app: deis-nsqd
